name: Build Lugaru

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y build-essential libsdl2-dev libopenal-dev libogg-dev libvorbis-dev libjpeg-dev libpng-dev zlib1g-dev cmake

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install openal
        choco install sdl2

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -S .

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Run tests
      working-directory: build
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lugaru-build-${{ matrix.os }}-${{ matrix.c_compiler }}
        path: build
