name: CMake build on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [native, windows]
        build_type: [Release]
        include:
          - target: native
            c_compiler: gcc
            cpp_compiler: g++
          - target: windows
            c_compiler: x86_64-w64-mingw32-gcc
            cpp_compiler: x86_64-w64-mingw32-g++

    steps:
    - uses: actions/checkout@v4

    # Install dependencies on Ubuntu for native build
    - name: Install dependencies (Ubuntu - Native)
      if: matrix.target == 'native'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ cmake make \
          libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
          libopenal-dev libsdl2-dev libvorbis-dev libogg-dev \
          libpng-dev libjpeg-dev

    # Install dependencies on Ubuntu for cross-compiling to Windows
    - name: Install dependencies (Ubuntu - Windows)
      if: matrix.target == 'windows'
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 \
          binutils-mingw-w64-x86-64 \
          gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 \
          cmake make autoconf automake libtool pkg-config

    # Build and install libogg for cross-compiling
    - name: Build libogg for Windows
      if: matrix.target == 'windows'
      run: |
        wget https://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.gz
        tar -xzf libogg-1.3.5.tar.gz
        cd libogg-1.3.5
        ./configure --host=x86_64-w64-mingw32 --prefix=${{ github.workspace }}/external/libogg --disable-shared
        make
        make install

    # Build and install libvorbis for cross-compiling
    - name: Build libvorbis for Windows
      if: matrix.target == 'windows'
      run: |
        wget https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.gz
        tar -xzf libvorbis-1.3.7.tar.gz
        cd libvorbis-1.3.7
        ./configure --host=x86_64-w64-mingw32 --prefix=${{ github.workspace }}/external/libvorbis --disable-shared
        make
        make install

    # Download precompiled Zlib, PNG, and JPEG libraries for Windows cross-compiling
    - name: Download Zlib, PNG, and JPEG libraries
      if: matrix.target == 'windows'
      run: |
        wget -q -O zlib-windows.zip "https://sourceforge.net/projects/gnuwin32/files/zlib/1.2.3/zlib-1.2.3-bin.zip/download"
        wget -q -O png-windows.zip "https://sourceforge.net/projects/gnuwin32/files/libpng/1.2.37/libpng-1.2.37-bin.zip/download"
        wget -q -O jpeg-windows.zip "https://sourceforge.net/projects/gnuwin32/files/jpeg/6b-4/jpeg-6b-4-bin.zip/download"
        unzip zlib-windows.zip -d ${{ github.workspace }}/external/zlib
        unzip png-windows.zip -d ${{ github.workspace }}/external/png
        unzip jpeg-windows.zip -d ${{ github.workspace }}/external/jpeg

    # Set reusable strings
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    # Configure CMake for native build
    - name: Configure CMake (Ubuntu - Native)
      if: matrix.target == 'native'
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DINCLUDE_DIRECTORIES=${{ github.workspace }}/external \
          -S ${{ github.workspace }}

    # Configure CMake for cross-compiling to Windows
    - name: Configure CMake (Ubuntu - Windows)
      if: matrix.target == 'windows'
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_SYSTEM_NAME=Windows \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DZLIB_LIBRARY=${{ github.workspace }}/external/zlib/lib/zlib.lib \
          -DZLIB_INCLUDE_DIR=${{ github.workspace }}/external/zlib/include \
          -DPNG_LIBRARY=${{ github.workspace }}/external/png/lib/libpng.lib \
          -DPNG_PNG_INCLUDE_DIR=${{ github.workspace }}/external/png/include \
          -DJPEG_LIBRARY=${{ github.workspace }}/external/jpeg/lib/jpeg.lib \
          -DJPEG_INCLUDE_DIR=${{ github.workspace }}/external/jpeg/include \
          -DVORBIS_LIBRARY=${{ github.workspace }}/external/libvorbis/lib/libvorbis.a \
          -DVORBIS_INCLUDE_DIR=${{ github.workspace }}/external/libvorbis/include \
          -DOGG_LIBRARY=${{ github.workspace }}/external/libogg/lib/libogg.a \
          -DOGG_INCLUDE_DIR=${{ github.workspace }}/external/libogg/include \
          -S ${{ github.workspace }}

    # Build
    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    # Test
    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
